version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: fisio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: fisio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fisio-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: fisio-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fisio.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fisio-network

volumes:
  postgres_data:

networks:
  fisio-network:
    driver: bridge
